# Generated by Django 3.2.8 on 2021-10-27 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_auto_20211027_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 14, 57, 38, 188888, tzinfo=utc)),
        ),
    ]
