# Generated by Django 3.2.8 on 2021-10-27 15:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_alter_notemodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionmodel',
            name='note',
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.collectionmodel'),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 15, 13, 27, 967544, tzinfo=utc)),
        ),
    ]
