# Generated by Django 3.2.8 on 2021-10-27 15:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_auto_20211027_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 27, 15, 14, 10, 445501, tzinfo=utc)),
        ),
    ]
