# Generated by Django 3.2.8 on 2021-10-24 05:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('desc', models.CharField(max_length=80)),
                ('fav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=80)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.notemodel')),
            ],
        ),
    ]
